name: Deploy App

on:
  push:
    tags:
      - App-v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production-App

    env:
      CONTAINER_NAME: host
      PORT: 5000

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          touch .env
          echo "VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}" >> .env
          echo "VITE_KAKAO_RESTAPI_KEY=${{ secrets.VITE_KAKAO_RESTAPI_KEY }}" >> .env
          echo "VITE_REDIRECT_URL=${{ secrets.VITE_REDIRECT_URL }}" >> .env

      - name: Get the version
        id: get_version
        run: |
          RELEASE_VERSION_WITHOUT_V="$(cut -d'v' -f2 <<< ${GITHUB_REF#refs/*/})"
          echo ::set-output name=VERSION::$RELEASE_VERSION_WITHOUT_V

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2.9.0

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image and Push DockerHub
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile.${{ env.CONTAINER_NAME }}
          platforms: linux/amd64
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{ env.CONTAINER_NAME }}:${{ steps.get_version.outputs.VERSION }}

      - name: Application Run
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}

          script: |
            sudo docker kill ${{ env.CONTAINER_NAME }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ steps.get_version.outputs.VERSION }}

            sudo docker run -it --rm -p ${{ env.PORT }}:${{ env.PORT }} \
            --name ${{ env.CONTAINER_NAME }} \
            -d ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ steps.get_version.outputs.VERSION }}
