name: Test Code by Jest

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2

      - name: Check Node
        run: node -v

      - name: Check npm
        run: npm -v

      - name: Install Dependencies
        run: npm install --frozen-lockfile

      - name: Run Test
        run: npm test
